export const LetoaDiscordAPIErrors = {
    DISCORD_NOT_LINKED: 5006,
    ALREADY_LINKED_TO_ANOTHER_LETOA_ACCOUNT: 5007,
    MISSING_ACCESS: 5008,
    BOT_NOT_IN_SERVER: 5009,
    SETUP_NOT_VALID: 5010,
    INVALID_ROLE_PROVIDED: 5011,
    MEMBER_NOT_IN_SERVER: 5012,
    USER_NOT_LOGGED_IN: 5013,
    INVALID_GUILD: 5014,
    INVALID_CHANNEL_PROVIDED: 5015,
    PROVIDED_ROLE_NOT_ACCESSABLE: 5016,
    CUSTOM_LINK_ALREADY_EXISTS: 5017,
    INVALID_TYPE: 5018,
    OWNER_REQUIRED: 5019,
    ALREADY_LINKED_TO_ACCOUNT: 5020,
    VPN_PROXY_DETECTED: 5021,
    BLACKLISTED_CUSTOM_LINK: 5022,
    PREMIUM_ALREADY_ACTIVATED: 5023,
    INVALID_ACCESS_TO_ACTIVATE: 5024,
    INVALID_PREMIUM_LEVEL: 5025,
    TOO_MANY_ACTIVATED_SERVERS: 5026,
    SERVER_NOT_ACTIVATED: 5027,
    INVALID_ACCESS_TO_DEACTIVATE: 5028,
    INVALID_DOMAIN: 5029,
    CUSTOM_DOMAIN_ALREADY_EXISTS: 5030,
};

export const CustomBotsErrorCodes = {
    INVALID_BOT_TOKEN: 1337,
    INVALID_CLIENT_ID: 1338,
    INVALID_CLIENT_SECRET: 1339,
    BOT_NOT_ALLOWED_INTENTS: 1340,
    INVALID_CONFIG: 1341,
    INVALID_ACTIVE_SERVER: 1342,
    INVALID_PERMISSIONS_FOR_ACTIVE_SERVER: 1343,
};

export const MiddlewareCodes = {
    INVALID_AUTHORIZATION: 1,
    AUTHORIZATION_NOT_PROVIDED: 2,
};

export const DiscordChannelTypes = {
    GUILD_TEXT_CHANNEL: 0,
    GUILD_VOICE: 2,
    GUILD_CATEGORY: 4,
    GUILD_NEWS: 5,
};

export const DiscordErrorCodes = {
    INVALID_ACCESS_TOKEN: 50025,
};
